In [1]:
import numpy as np

In [2]:
#1
a = np.array([[1,5,3],
              [9,7,6]])
a

array([[1, 5, 3],
       [9, 7, 6]])

In [4]:
#converting to 1D
b = a.reshape(6,)
b

array([1, 5, 3, 9, 7, 6])

In [6]:
#2
c = np.array([[3,2,1],
              [7,3,1],
              [4,9,7]])
c.flatten()

array([3, 2, 1, 7, 3, 1, 4, 9, 7])

In [8]:
#3
a = np.array([[[1,2],
              [4,6]],
              [[5,2],
               [2,5]]])
print(a)
a.flatten()

[[[1 2]
  [4 6]]

 [[5 2]
  [2 5]]]


array([1, 2, 4, 6, 5, 2, 2, 5])

In [10]:
#4
a = np.array([[1,4,3],
              [5,4,7]])
print(a.shape)
b = a.flatten()
print(b.shape)

(2, 3)
(6,)


In [12]:
#5
a = np.array([[10,20],
              [30,40],
              [50,60]])
print(a.flatten())

[10 20 30 40 50 60]


In [13]:
#6
s = np.array([1,5,4,8,6,7,5,2])
b = s.reshape(1,4,2)
print(b)
c = s.reshape(2,4)
print(c)

[[[1 5]
  [4 8]
  [6 7]
  [5 2]]]
[[1 5 4 8]
 [6 7 5 2]]


In [14]:
#mathematical operations

a = np.array([2,4,6])
b = np.array([1,3,5])
c = np.add(a,b)
print(c)
d = np.subtract(a,b)
print(d)
e = np.multiply(a,b)
f = np.divide(a,b)
print(f)
h = np.dot(a,b)
print(h)


[ 3  7 11]
[1 1 1]
[2.         1.33333333 1.2       ]
44


In [15]:
a = np.array([12,5,30,18,9])
a.max()

np.int64(30)

In [16]:
a.min()

np.int64(5)

In [17]:
c = np.sum(a)
print(c)

74


In [19]:
d = np.mean(a)
print(d)


14.8


In [20]:
a.argmin()

np.int64(1)

In [21]:
a.argmax()

np.int64(2)

In [22]:
a = np.array([[2,3,1],
             [4,5,6]])
a.max(axis = 0)


array([4, 5, 6])

In [23]:
a.max(axis = 1)

array([3, 6])

In [24]:
a.min(axis = 0)

array([2, 3, 1])

In [25]:
a.min(axis = 1)

array([1, 4])

In [26]:
a.sum(axis = 0)

array([6, 8, 7])

In [27]:
a.sum(axis = 1)

array([ 6, 15])

In [28]:
a = np.array([5,10,15,20,25,30])
a[0]

np.int64(5)

In [29]:
a[1:5]

array([10, 15, 20, 25])

In [30]:
a[0:4]

array([ 5, 10, 15, 20])

In [31]:
a[1:6:2]

array([10, 20, 30])

In [32]:
a[::-1]

array([30, 25, 20, 15, 10,  5])

In [33]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a[1,2]

np.int64(6)

In [34]:
a[0]

array([1, 2, 3])

In [35]:
a[:1]

array([[1, 2, 3]])

In [36]:
a[2]

array([7, 8, 9])

In [37]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [39]:
a = np.array([[[1,2,3],
              [4,5,6]],
              
              [[7,8,9],
               [10,11,12]]])
a[0]
              

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [41]:
a[0,0]

array([1, 2, 3])

In [42]:
a[1,1]

array([10, 11, 12])

In [43]:
a[1,1,1]

np.int64(11)

In [44]:
a[-1,-1,-1]

np.int64(12)

In [45]:
a[0,0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [48]:
a[:,0:2,1:2]

array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]])

In [49]:
a[:,:,1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [50]:
a[:,:,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [51]:
a[:,:,::-1]

array([[[ 3,  2,  1],
        [ 6,  5,  4]],

       [[ 9,  8,  7],
        [12, 11, 10]]])

In [54]:
#submatrix operations
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12],
           [13,14,15,16]])
a[0:2,0:2]


array([[1, 2],
       [5, 6]])

In [56]:
a[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [57]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [58]:
a[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [59]:
a[1:3,0:3]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [60]:
a[0:3,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [61]:
a[2:3,:]

array([[ 9, 10, 11, 12]])

In [62]:
a[:,3:4]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [64]:
a[0:3:2,0:3:2]

array([[ 1,  3],
       [ 9, 11]])

In [65]:
a[1:4,1:4]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])