In [ ]:
# numpy is an open source python that widely used in engineering and science.it was created in 2005 by Travis Oliphant.
# Numerical python is a library that provides support for large,multi-dimensional arrays and matrices,along with a collection of
# mathematical functions to operate on arrays.

# Features

#    N-dimensional array
#    Mathematical functions-operations on arrays
#    Integration with other libraries
#    Random number generation

# Advantages
                                                                                                   
#     Faster than python lists
#     Supports multidimesional arrays   
#     Memory efficient                                                                                                 
#     Provides a lot of supporting functions
                                                                                                 

In [ ]:
# Numpy arrays are stored at one continuous place in memory,so processes can access and manipulate them very efficiently.
# Memory efficiency : Numpy use a  more compact representation,loading to lower memory consumption compared to lists.
# Homogeneous datatype   

In [ ]:
 # ndim : number of dimensions of array
 #  shape : size of array in each dimension
 #  size : total no of elements in the array
 #  dtype : data type of array elements 
 #  type() : type of the object

In [ ]:
  # a) pytho n - lists - it can be store different datatypes like int ,float,string etc.Slower for numerical operations  and uses more memory
  #     Numpy array - Stores elements of the same data types.Faster for numerical operations and more memory efficient.

  # b) Shape - gives the  dimensions of array as tuple
  #    size  - gives the total number of elements
      
  # c) dtype - returns dsta type of array elements
  #    type() - returns the type of the object

In [ ]:
# a represents the layer, b represents rows and c represents columns.

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
12
int64
<class 'numpy.ndarray'>


In [3]:
b = np.array([
      [7,8,4],
      [4,5,3],
      [2,3,1],
      [6,5,4],
      [8,2,1],
      [9,4,2]
  ]
              )
print(b)
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)
print(type(b))


[[7 8 4]
 [4 5 3]
 [2 3 1]
 [6 5 4]
 [8 2 1]
 [9 4 2]]
2
18
(6, 3)
int64
<class 'numpy.ndarray'>


In [8]:
d = np.array([
    [[1,3],
     [6,3],
     [3,1],
     [8,1]],

    [[2,4],
     [9,0],
     [8,6],
     [4,1]],

    [[8,3],
         [1,9],
         [4,7],
         [5,2]]
]
             )
    
         
     
print(d)
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)
print(type(d))

[[[1 3]
  [6 3]
  [3 1]
  [8 1]]

 [[2 4]
  [9 0]
  [8 6]
  [4 1]]

 [[8 3]
  [1 9]
  [4 7]
  [5 2]]]
3
(3, 4, 2)
24
int64
<class 'numpy.ndarray'>


In [10]:
c = np.array([
    [[1,2,3,4,6,7],
     [9,5,4,2,6,5],
     [6,4,9,6,7,2],
     [3,2,1,7,9,6]],

     [[32,5,53,11,7,5],
      [7,4,3,8,9,3],
      [3,5,7,1,9,8],
      [4,3,8,65,12,7]]
    ]
    )
print(c)
print(c.ndim)
print(c.size)
print(c.shape)
print(c.dtype)

[[[ 1  2  3  4  6  7]
  [ 9  5  4  2  6  5]
  [ 6  4  9  6  7  2]
  [ 3  2  1  7  9  6]]

 [[32  5 53 11  7  5]
  [ 7  4  3  8  9  3]
  [ 3  5  7  1  9  8]
  [ 4  3  8 65 12  7]]]
3
48
(2, 4, 6)
int64
