In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3])
print(arr + 5)
print(arr * 2)

[6 7 8]
[2 4 6]


In [6]:
matrix = np.array([[1,2],[3,4]])
vector = np.array([5,6])
print(matrix + vector)

[[ 6  8]
 [ 8 10]]


In [5]:
np.zeros((2,3,6),dtype='int')

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [7]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
np.eye(5,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [9]:
np.eye(5,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
np.linspace(0,1)# evenly spaced numbers

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [15]:
np.linspace(0,1,15)# evenly spaced numbers

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [17]:
arr = np.array([1,2,3,4,5])
b = arr > 2
print(b)
print(arr[b])

[False False  True  True  True]
[3 4 5]


In [18]:
arr = np.array([1,2,3,4,5])
new_arr = np.where(arr % 2 == 0,arr,-1)
print(new_arr)

[-1  2 -1  4 -1]


In [19]:
matrix = np.array([[1,2],[3,4]])
print(np.mean(matrix))
print(np.max(matrix))
print(np.sum(matrix))

2.5
4
10


In [20]:
a=np.diag([3,4,32,2])
a

array([[ 3,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 32,  0],
       [ 0,  0,  0,  2]])

In [23]:
np.random.seed(2)
a = np.random.random((2,))
print(a)

[0.4359949  0.02592623]


In [27]:
a = np.random.randint(2,12,(2,3))
a

array([[ 8,  4, 10],
       [ 9,  4,  3]], dtype=int32)