In [1]:
import numpy as np


In [2]:
a=np.array([1,2,4,3,5,6])
a.shape

(6,)

In [4]:
#@ 1D to 2D
a=np.array([2,1,4,5,6,2])
b=a.reshape(2,3) #(1,6),(6,1),(3,2)
print(a)
print(b)

[2 1 4 5 6 2]
[[2 1 4]
 [5 6 2]]


In [5]:
#1D TO 3D
c=np.array([1,2,4,3,5,7])
d=c.reshape(1,2,3)
print(d)

[[[1 2 4]
  [3 5 7]]]


In [6]:
# 2D to 1D
a=np.array([[1,2],[3,4],[5,6],[8,7]])
e=a.reshape(8,)
e

array([1, 2, 3, 4, 5, 6, 8, 7])

In [7]:
#3D to 2D
a=np.array([[[2,3],[1,4],[5,7],[4,3]]])
b=a.reshape(4,2)
print(b)

[[2 3]
 [1 4]
 [5 7]
 [4 3]]


In [9]:
#3D to 3D
a=np.array([[[2,3],[1,4],[5,7],[4,3]]])
b=a.reshape(1,2,4)
print(b)

[[[2 3 1 4]
  [5 7 4 3]]]


In [10]:
#2D to 3D
a=np.array([[2,3],[1,4],[5,7],[4,3]])
b=a.reshape(1,2,4)
b

array([[[2, 3, 1, 4],
        [5, 7, 4, 3]]])

In [11]:
#2D to 2D
a=np.array([[2,3],[1,4],[5,7],[4,2]])
b=a.reshape(4,2)
b

array([[2, 3],
       [1, 4],
       [5, 7],
       [4, 2]])

In [12]:
#3 D to 1D 
a=np.array([[[2,3],[1,4],[5,7],[4,3]]])
c=a.reshape(8,)
print(c)

[2 3 1 4 5 7 4 3]


In [14]:
a=np.array([[[2,3],[1,4],[5,7],[4,3]]])
print(c)
a.flatten()


[2 3 1 4 5 7 4 3]


array([2, 3, 1, 4, 5, 7, 4, 3])

In [15]:
a.reshape(-1)


array([2, 3, 1, 4, 5, 7, 4, 3])

In [16]:
a=np.array([5,4])
b=np.array([6,4])
c=np.add(a,b)
c

array([11,  8])

In [19]:
c=np.subtract(a,b)
c

array([-1,  0])

In [20]:
c=np.multiply(a,b)
c

array([30, 16])

In [21]:
c=np.dot(a,b)
c

np.int64(46)

In [23]:
a = np.array([1,5,80,6,43])
a.max()

np.int64(80)

In [25]:
a.min()

np.int64(1)

In [26]:
a.argmax()

np.int64(2)

In [27]:
a.argmin()

np.int64(0)

In [29]:
a.argmin(axis=0)

np.int64(0)

In [32]:
a.argmax(axis=0)#column 

np.int64(2)

In [34]:
a = np.array([1,5,80,6,43])
b=a.copy()
b

array([ 1,  5, 80,  6, 43])

In [35]:
a[0]=4
a

array([ 4,  5, 80,  6, 43])

In [36]:
b

array([ 1,  5, 80,  6, 43])

In [ ]:
a=np.array([7,8,6])

In [37]:
a[0]

np.int64(4)

In [38]:
a[0:2]

array([4, 5])

In [39]:
a[-3:-1]

array([80,  6])

In [44]:
a=np.array([
    [1,2],
    [6,9]
]
          )
a

array([[1, 2],
       [6, 9]])

In [45]:
a[0,1]

np.int64(2)

In [46]:
a[-2,-1]

np.int64(2)

In [49]:
a=np.array([
    [1,2,6],
    [6,2,3]
]
          )
a

array([[1, 2, 6],
       [6, 2, 3]])

In [50]:
a[0,2]

np.int64(6)

In [51]:
a[1,2]

np.int64(3)

In [54]:
c=np.array(
    [
        [[1,2,3],
        [4,5,6]],

        [[8,9,7],
        [4,5,6]],

        [[4,6,2],
        [4,5,9]],

    ]
)
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[8, 9, 7],
        [4, 5, 6]],

       [[4, 6, 2],
        [4, 5, 9]]])

In [61]:
c[1,0,1]

np.int64(9)

In [62]:
c[-1,-2,-1]

np.int64(2)

In [63]:
c[0,0:2,1:3]

array([[2, 3],
       [5, 6]])

In [64]:
c=np.array(
    [
        [1,2,3,5],
        [4,5,6,9],
        [8,2,1,10],
    ]
)
c

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  9],
       [ 8,  2,  1, 10]])

In [65]:
c[1:3,1:3]

array([[5, 6],
       [2, 1]])

In [68]:
c[1:3,0:2]

array([[4, 5],
       [8, 2]])